@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

FoodInventory *-right-> "1" UniqueFoodList
FoodInventory *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniqueFoodList
UniqueTagList -[hidden]down- UniqueFoodList

UniqueTagList *-right-> "*" Tag
UniqueFoodList o-right-> Food

Food -up-> "*" Tag

Food *--> Description
Food *--> ExpiryDate
Food *--> Priority
Food *--> Quantity
@enduml
