@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyFoodInventory <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class FoodInventory
Class ReadOnlyFoodInventory
Class VersionedFoodInventory
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Package Food {
Class Food
Class Description
Class ExpiryDate
Class Priority
Class Quantity
Class UniqueFoodList
}

Package Tag {
Class Tag
}
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

FoodInventory .up.|> ReadOnlyFoodInventory
VersionedFoodInventory .up.|> FoodInventory

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" VersionedFoodInventory
ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

VersionedFoodInventory *--> "1" UniqueFoodList
UniqueFoodList o--> "*" Food
Food *--> Description
Food *--> ExpiryDate
Food *--> Priority
Food *--> Quantity
Food *--> "*" Tag

Description -[hidden]right-> ExpiryDate
ExpiryDate -[hidden]right-> Priority
Priority -[hidden]right-> Quantity

ModelManager -->"1" Food : filtered list
@enduml
