@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":FoodInventoryParser" as FoodInventoryParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedFoodInventory" as VersionedFoodInventory MODEL_COLOR
end box
[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> FoodInventoryParser : parseCommand(undo)
activate FoodInventoryParser

create UndoCommand
FoodInventoryParser -> UndoCommand
activate UndoCommand

UndoCommand --> FoodInventoryParser
deactivate UndoCommand

FoodInventoryParser --> LogicManager : u
deactivate FoodInventoryParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoFoodInventory()
activate Model

Model -> VersionedFoodInventory : undo()
activate VersionedFoodInventory

VersionedFoodInventory -> VersionedFoodInventory :resetData(ReadOnlyFoodInventory)
VersionedFoodInventory --> Model :
deactivate VersionedFoodInventory

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
